change Jenkins file

diff --git a/Backend/project/Jenkinsfile b/Backend/project/Jenkinsfile
--- a/Backend/project/Jenkinsfile
+++ b/Backend/project/Jenkinsfile
@@ -65,4 +65,16 @@ pipeline {
 
     post {
         success {
-            echo '
+            echo 'Build successfully!'
+        }
+        failure {
+            echo 'Build failed!'
+        }
+        always {
+            script {
+                sh "docker rm -f ${DOCKER_IMAGE} || true"
+                sh "docker rmi ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${env.BUILD_NUMBER} || true"
+            }
+        }
+    }
+}
