change Jenkins file

diff --git a/Backend/project/Jenkinsfile b/Backend/project/Jenkinsfile
--- a/Backend/project/Jenkinsfile
+++ b/Backend/project/Jenkinsfile
@@ -3,42 +3,40 @@ pipeline {
     environment {
         DOCKER_IMAGE = 'app'
         DOCKER_REGISTRY = 'haquocviet'
-        PATH = "${tool 'Docker'}/bin:${env.PATH}"
+        PATH = "${tool 'Docker'}/bin:${env.PATH}:~/.local/bin"
     }
     stages {
         stage('Initialize') {
             steps {
                 script {
                     def dockerHome = tool 'Docker'
-                    env.PATH = "${dockerHome}/bin:${env.PATH}"
+                    env.PATH = "${dockerHome}/bin:${env.PATH}:~/.local/bin"
                 }
             }
         }
         stage('Install Docker Compose') {
-               steps {
-                   dir('Backend/project') {
-                       script {
-                       // Check if docker-compose is already installed
-                            def dockerComposeInstalled = sh(script: 'command -v docker-compose', returnStatus: true) == 0
+            steps {
+                dir('Backend/project') {
+                    script {
+                        def dockerComposeInstalled = sh(script: 'command -v docker-compose', returnStatus: true) == 0
 
-                            if (!dockerComposeInstalled) {
-                                echo 'Docker Compose not found, installing...'
-                                sh '''
-                                    curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
-                                    chmod +x ~/docker-compose
-                                    mkdir -p ~/.local/bin
-                                     mv ~/docker-compose ~/.local/bin/docker
-                                '''
-                       } else {
-                           echo 'Docker Compose is already installed.'
-                       }
-                       sh '~/.local/bin/docker --version'
-                       }
-                   }
-               }
-
+                        if (!dockerComposeInstalled) {
+                            echo 'Docker Compose not found, installing...'
+                            sh '''
+                                curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
+                                chmod +x ~/docker-compose
+                                mkdir -p ~/.local/bin
+                                mv ~/docker-compose ~/.local/bin/docker-compose
+                            '''
+                        } else {
+                            echo 'Docker Compose is already installed.'
+                        }
+                        sh 'export PATH=$PATH:~/.local/bin'
+                        sh '~/.local/bin/docker-compose --version'
+                    }
+                }
+            }
         }
-
         stage('Checkout') {
             steps {
                 checkout([
@@ -76,12 +74,10 @@ pipeline {
         stage('Push Docker Image') {
             steps {
                 script {
-                    // Push Docker image lên Docker registry
                     withDockerRegistry(credentialsId: 'haquocviet', toolName: 'Docker', url: 'https://index.docker.io/v1/') {
                         sh "docker tag ${DOCKER_IMAGE}:${env.BUILD_NUMBER} ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${env.BUILD_NUMBER}"
                         sh "docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${env.BUILD_NUMBER}"
                     }
-
                 }
             }
         }
@@ -89,7 +85,7 @@ pipeline {
             steps {
                 dir('Backend/project') {
                     script {
-                        sh 'which docker-compose || { echo " Cannot find docker-compose."; exit 1; }'
+                        sh 'if ! command -v docker-compose; then echo "docker-compose not found"; exit 1; fi'
                         sh 'docker-compose down'
                         sh 'docker-compose up -d'
                     }
